[workspace]
resolver = "2"

members = [
    "01_variables",
    "02_mutability",
    "03_data_types",
    "04_functions",
    "05_control_flow",
    "06_ownership",
    "07_borrowing",
    "08_slices",
    "09_structs",
    "10_enums",
    "11_pattern_matching",
    "12_collections",
    "13_error_handling",
    "14_traits",
    "15_generics",
    "16_lifetimes",
    "17_modules",
    "18_iterators",
    "19_closures",
    "20_smart_pointers",
]
